# Generated by Django 4.2.16 on 2026-03-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("localisation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="latitude_centre",
        ),
        migrations.RemoveField(
            model_name="district",
            name="longitude_centre",
        ),
        migrations.RemoveField(
            model_name="pays",
            name="latitude_centre",
        ),
        migrations.RemoveField(
            model_name="pays",
            name="longitude_centre",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="province",
            name="latitude_centre",
        ),
        migrations.RemoveField(
            model_name="province",
            name="longitude_centre",
        ),
        migrations.RemoveField(
            model_name="quartier",
            name="latitude_centre",
        ),
        migrations.RemoveField(
            model_name="quartier",
            name="longitude_centre",
        ),
    ]
