# Generated by Django 4.2.16 on 2026-03-01 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("localisation", "0002_supprimer_colonnes_coordonnees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("nom", models.CharField(db_index=True, max_length=200)),
                ("type_colline", models.CharField(default="COLLINE", max_length=50)),
                (
                    "centre_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "centre_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("population_estimee", models.IntegerField(blank=True, null=True)),
                ("zone_rurale", models.BooleanField(db_index=True, default=True)),
                ("autorise_systeme", models.BooleanField(db_index=True, default=True)),
                ("est_actif", models.BooleanField(db_index=True, default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Colline",
                "verbose_name_plural": "Collines",
                "db_table": 'localisation"."collines',
                "ordering": ["zone__nom", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("nom", models.CharField(db_index=True, max_length=200)),
                ("type_commune", models.CharField(default="COMMUNE", max_length=50)),
                (
                    "centre_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "centre_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "bbox_nord",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "bbox_sud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "bbox_est",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "bbox_ouest",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "superficie_km2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("population_totale", models.BigIntegerField(blank=True, null=True)),
                ("zone_urbaine", models.BooleanField(db_index=True, default=False)),
                ("autorise_systeme", models.BooleanField(db_index=True, default=True)),
                ("est_actif", models.BooleanField(db_index=True, default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "db_table": 'localisation"."communes',
                "ordering": ["district__nom", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("nom", models.CharField(db_index=True, max_length=200)),
                ("type_secteur", models.CharField(default="SECTEUR", max_length=50)),
                (
                    "centre_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "centre_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("population_estimee", models.BigIntegerField(blank=True, null=True)),
                ("zone_urbaine", models.BooleanField(db_index=True, default=False)),
                ("autorise_systeme", models.BooleanField(db_index=True, default=True)),
                ("est_actif", models.BooleanField(db_index=True, default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "db_table": 'localisation"."secteurs',
                "ordering": ["commune__nom", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("nom", models.CharField(db_index=True, max_length=200)),
                ("type_zone", models.CharField(default="ZONE", max_length=50)),
                (
                    "centre_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "centre_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("population_estimee", models.IntegerField(blank=True, null=True)),
                ("zone_commerciale", models.BooleanField(db_index=True, default=False)),
                (
                    "zone_residentielle",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("autorise_systeme", models.BooleanField(db_index=True, default=True)),
                ("est_actif", models.BooleanField(db_index=True, default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "db_table": 'localisation"."zones',
                "ordering": ["quartier__nom", "nom"],
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["province__nom", "nom"],
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.AlterModelOptions(
            name="pays",
            options={
                "ordering": ["nom"],
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
            },
        ),
        migrations.AlterModelOptions(
            name="pointdeservice",
            options={
                "ordering": ["quartier__nom", "nom"],
                "verbose_name": "Point de service",
                "verbose_name_plural": "Points de service",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["pays__nom", "nom"],
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.AlterModelOptions(
            name="quartier",
            options={
                "ordering": ["district__nom", "nom"],
                "verbose_name": "Quartier",
                "verbose_name_plural": "Quartiers",
            },
        ),
        migrations.RemoveIndex(
            model_name="pays",
            name="pays_contine_f2ca79_idx",
        ),
        migrations.RemoveIndex(
            model_name="pays",
            name="pays_sous_re_a6efd2_idx",
        ),
        migrations.RemoveIndex(
            model_name="pays",
            name="pays_code_is_bf11fe_idx",
        ),
        migrations.RemoveField(
            model_name="district",
            name="nombre_agents_actifs",
        ),
        migrations.RemoveField(
            model_name="district",
            name="nombre_utilisateurs_actifs",
        ),
        migrations.RemoveField(
            model_name="pays",
            name="nombre_agents_actifs",
        ),
        migrations.RemoveField(
            model_name="pays",
            name="nombre_utilisateurs_actifs",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="adresse_complementaire",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="agent_utilisateur",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="nombre_agents",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="nombre_agents_actifs",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="nombre_utilisateurs",
        ),
        migrations.RemoveField(
            model_name="pointdeservice",
            name="nombre_utilisateurs_actifs",
        ),
        migrations.RemoveField(
            model_name="province",
            name="nombre_agents_actifs",
        ),
        migrations.RemoveField(
            model_name="province",
            name="nombre_utilisateurs_actifs",
        ),
        migrations.RemoveField(
            model_name="quartier",
            name="nombre_agents_actifs",
        ),
        migrations.RemoveField(
            model_name="quartier",
            name="nombre_utilisateurs_actifs",
        ),
        migrations.AddField(
            model_name="district",
            name="bbox_est",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="bbox_nord",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="bbox_ouest",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="bbox_sud",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="centre_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="centre_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="population_estimee",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="superficie_km2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="bbox_est",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="bbox_nord",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="bbox_ouest",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="bbox_sud",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="centre_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="centre_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="code_telephonique",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="pays",
            name="devise_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="pays",
            name="devise_nom",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pays",
            name="population_estimee",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="superficie_km2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="bbox_est",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="bbox_nord",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="bbox_ouest",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="bbox_sud",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="centre_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="centre_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="population_estimee",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="province",
            name="superficie_km2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="centre_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="centre_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="autorise_systeme",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="district",
            name="est_actif",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="nom",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="district",
            name="nombre_agents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="district",
            name="nombre_utilisateurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pays",
            name="autorise_systeme",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="pays",
            name="code_iso_3",
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="pays",
            name="continent",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pays",
            name="est_actif",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="pays",
            name="nom",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pays",
            name="nombre_agents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pays",
            name="nombre_utilisateurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pays",
            name="sous_region",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pointdeservice",
            name="autorise_systeme",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="pointdeservice",
            name="code",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="pointdeservice",
            name="est_actif",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="pointdeservice",
            name="nom",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="province",
            name="autorise_systeme",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="province",
            name="est_actif",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="province",
            name="nom",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="province",
            name="nombre_agents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="province",
            name="nombre_utilisateurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="autorise_systeme",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="est_actif",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="nom",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="nombre_agents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="nombre_utilisateurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                fields=["province", "est_actif"], name="districts_provinc_d04c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pays",
            index=models.Index(
                fields=["est_actif", "autorise_systeme"], name="pays_est_act_3da8ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pays",
            index=models.Index(
                fields=["continent", "sous_region"], name="pays_contine_fdcf46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointdeservice",
            index=models.Index(
                fields=["quartier", "est_actif"], name="points_de_s_quartie_9421e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointdeservice",
            index=models.Index(
                fields=["type_point"], name="points_de_s_type_po_b59e19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="province",
            index=models.Index(
                fields=["pays", "est_actif"], name="provinces_pays_id_1080c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quartier",
            index=models.Index(
                fields=["district", "est_actif"], name="quartiers_distric_51be7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quartier",
            index=models.Index(fields=["secteur"], name="quartiers_secteur_027239_idx"),
        ),
        migrations.AddField(
            model_name="zone",
            name="quartier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="localisation.quartier",
            ),
        ),
        migrations.AddField(
            model_name="secteur",
            name="commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secteurs",
                to="localisation.commune",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="localisation.district",
            ),
        ),
        migrations.AddField(
            model_name="colline",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collines",
                to="localisation.zone",
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="secteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quartiers",
                to="localisation.secteur",
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["quartier", "est_actif"], name="zones_quartie_251448_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zone",
            unique_together={("quartier", "code")},
        ),
        migrations.AddIndex(
            model_name="secteur",
            index=models.Index(
                fields=["commune", "est_actif"], name="secteurs_commune_4faae6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secteur",
            unique_together={("commune", "code")},
        ),
        migrations.AddIndex(
            model_name="commune",
            index=models.Index(
                fields=["district", "est_actif"], name="communes_distric_f5ec03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commune",
            index=models.Index(
                fields=["zone_urbaine", "est_actif"], name="communes_zone_ur_6ff8ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commune",
            unique_together={("district", "code")},
        ),
        migrations.AddIndex(
            model_name="colline",
            index=models.Index(
                fields=["zone", "est_actif"], name="collines_zone_id_6699de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="colline",
            unique_together={("zone", "code")},
        ),
    ]
