# Generated by Django 4.2.16 on 2026-03-01 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "localisation",
            "0003_colline_commune_secteur_zone_alter_district_options_and_more",
        ),
    ]

    operations = [
        # Ajouter format_telephone au lieu de renommer (car devise_nom n'existe peut-être pas)
        migrations.AddField(
            model_name="pays",
            name="format_telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="district",
            name="code_bancaire",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="district",
            name="code_postal",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="district",
            name="couverture_reseau_mobile",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="geometrie_geojson",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="niveau_activite_economique",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="district",
            name="nombre_agences_bancaires",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="district",
            name="nombre_agents_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="district",
            name="nombre_agents_mobile_money",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="district",
            name="nombre_distributeurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="district",
            name="nombre_utilisateurs_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="district",
            name="zone_urbaine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pays",
            name="autorise_crypto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pays",
            name="autorise_mobile_money",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="code_swift_pays",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="pays",
            name="exige_kyc_renforce",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pays",
            name="fuseau_horaire_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="geometrie_geojson",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="indice_corruption",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="langue_principale",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pays",
            name="langues_secondaires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="limite_transaction_journaliere",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="limite_transaction_mensuelle",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="niveau_bancarisation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="niveau_risque_pays",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pays",
            name="nombre_agents_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pays",
            name="nombre_utilisateurs_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pays",
            name="pib_par_habitant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="score_facilite_affaires",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pays",
            name="systeme_bancaire",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pays",
            name="taux_penetration_internet",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="taux_penetration_mobile",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="adresse_complementaire",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="agent_utilisateur_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="altitude_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="nombre_agents",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="nombre_agents_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="nombre_utilisateurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="nombre_utilisateurs_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pointdeservice",
            name="precision_gps_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="code_bancaire",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="province",
            name="couverture_internet",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="couverture_reseau_mobile",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="densite_population",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="geometrie_geojson",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="province",
            name="nombre_agences_bancaires",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="nombre_agents_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="nombre_banques",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="nombre_distributeurs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="nombre_utilisateurs_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="zone_urbaine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quartier",
            name="bbox_est",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="bbox_nord",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="bbox_ouest",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="bbox_sud",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="code_postal",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="quartier",
            name="geometrie_geojson",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quartier",
            name="nombre_agents_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quartier",
            name="nombre_commerces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quartier",
            name="nombre_habitants",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quartier",
            name="nombre_utilisateurs_actifs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quartier",
            name="superficie_km2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quartier",
            name="type_zone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
