# Generated by Django 4.2.16 on 2026-03-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("localisation", "0004_rename_devise_nom_pays_format_telephone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pays",
            name="devise_code",
        ),
        migrations.RemoveField(
            model_name="pays",
            name="devise_nom",
        ),
    ]
