# Generated by Django 4.2.16 on 2026-02-13 13:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('wallet_type', models.CharField(choices=[('PERSONAL', 'Personal Wallet'), ('BUSINESS', 'Business Wallet'), ('SAVINGS', 'Savings Wallet'), ('ESCROW', 'Escrow Wallet')], default='PERSONAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.currency')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=19)),
                ('inverse_rate', models.DecimalField(decimal_places=8, max_digits=19)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='wallets.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='wallets.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=19)),
                ('external_transaction_id', models.UUIDField()),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__3d47ad_idx'), models.Index(fields=['external_transaction_id'], name='wallet_tran_externa_3a6c4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('DAILY', 'Daily Limit'), ('WEEKLY', 'Weekly Limit'), ('MONTHLY', 'Monthly Limit'), ('YEARLY', 'Yearly Limit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_limits',
                'unique_together': {('wallet', 'limit_type', 'valid_from')},
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user_id'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallets_currenc_796236_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='wallets_status_5720bd_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='exchange_ra_from_cu_72b998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'valid_from')},
        ),
    ]
