# Generated by Django 4.2.16 on 2026-03-01 23:12

from django.db import migrations


def rename_indexes_safe(apps, schema_editor):
    """Renomme les index de manière sécurisée en ignorant les erreurs si l'index n'existe pas"""
    with schema_editor.connection.cursor() as cursor:
        # Liste des renommages d'index à effectuer
        renames = [
            ('authentific_numero__idx2', 'codes_confi_numero__aad9a6_idx'),
            ('authentific_code_idx', 'codes_confi_code_93046e_idx'),
            ('authentific_utilisa_idx2', 'codes_confi_utilisa_467528_idx'),
            ('authentific_date_ex_idx', 'codes_confi_date_ex_0ebe16_idx'),
            ('authentific_utilisa_idx', 'historique__utilisa_dd670c_idx'),
            ('authentific_courrie_idx', 'historique__courrie_c0aabc_idx'),
            ('authentific_numero__idx', 'historique__numero__318e1d_idx'),
            ('authentific_type_ch_idx', 'historique__type_ch_c7b803_idx'),
        ]
        
        for old_name, new_name in renames:
            try:
                cursor.execute(f'ALTER INDEX IF EXISTS {old_name} RENAME TO {new_name}')
            except Exception as e:
                print(f"Avertissement: Impossible de renommer l'index {old_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_indexes_safe, migrations.RunPython.noop),
    ]
