# Generated by Django 4.2.16 on 2026-02-13 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "courriel",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "numero_telephone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[1-9]\\d{1,14}$"
                            )
                        ],
                    ),
                ),
                ("hash_mot_de_passe", models.CharField(max_length=255)),
                ("prenom", models.CharField(default="", max_length=100)),
                ("nom_famille", models.CharField(default="", max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "lieu_naissance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("nationalite", models.CharField(default="BI", max_length=2)),
                ("pays_residence", models.CharField(default="BI", max_length=2)),
                ("province", models.CharField(blank=True, default="", max_length=100)),
                ("ville", models.CharField(blank=True, default="", max_length=100)),
                ("commune", models.CharField(blank=True, default="", max_length=100)),
                ("quartier", models.CharField(blank=True, default="", max_length=100)),
                ("avenue", models.CharField(blank=True, default="", max_length=100)),
                (
                    "numero_maison",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("adresse_complete", models.TextField(blank=True, default="")),
                (
                    "code_postal",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("telephone_verifie", models.BooleanField(default=False)),
                ("telephone_verifie_le", models.DateTimeField(blank=True, null=True)),
                ("courriel_verifie", models.BooleanField(default=False)),
                ("courriel_verifie_le", models.DateTimeField(blank=True, null=True)),
                (
                    "niveau_kyc",
                    models.IntegerField(
                        choices=[
                            (0, "Non vérifié"),
                            (1, "Basique"),
                            (2, "Complet"),
                            (3, "Premium"),
                        ],
                        default=0,
                    ),
                ),
                ("date_validation_kyc", models.DateTimeField(blank=True, null=True)),
                ("validateur_kyc_id", models.UUIDField(blank=True, null=True)),
                (
                    "type_utilisateur",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("AGENT", "Agent"),
                            ("MARCHAND", "Marchand"),
                            ("ADMIN", "Administrateur"),
                            ("SUPER_ADMIN", "Super Administrateur"),
                            ("SYSTEME", "Système"),
                        ],
                        default="CLIENT",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU", "Suspendu"),
                            ("BLOQUE", "Bloqué"),
                            ("FERME", "Fermé"),
                            ("EN_VERIFICATION", "En vérification"),
                        ],
                        db_index=True,
                        default="ACTIF",
                        max_length=20,
                    ),
                ),
                ("raison_statut", models.TextField(blank=True, default="")),
                ("nombre_tentatives_connexion", models.IntegerField(default=0)),
                ("bloque_jusqua", models.DateTimeField(blank=True, null=True)),
                ("double_auth_activee", models.BooleanField(default=False)),
                (
                    "secret_2fa",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("est_actif", models.BooleanField(db_index=True, default=True)),
                (
                    "date_creation",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("derniere_connexion", models.DateTimeField(blank=True, null=True)),
                (
                    "derniere_modification_mdp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cree_par", models.UUIDField(blank=True, null=True)),
                ("modifie_par", models.UUIDField(blank=True, null=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="identite_utilisateurs",
                        related_query_name="identite_utilisateur",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="identite_utilisateurs",
                        related_query_name="identite_utilisateur",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": 'identite"."utilisateurs',
            },
        ),
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url_avatar", models.URLField(blank=True, max_length=500)),
                ("url_photo_couverture", models.URLField(blank=True, max_length=500)),
                ("biographie", models.TextField(blank=True)),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("sw", "Kiswahili"),
                            ("rn", "Kirundi"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("devise_preferee", models.CharField(default="BIF", max_length=3)),
                (
                    "fuseau_horaire",
                    models.CharField(default="Africa/Bujumbura", max_length=50),
                ),
                ("format_date", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("format_heure", models.CharField(default="24h", max_length=10)),
                ("notifications_courriel", models.BooleanField(default=True)),
                ("notifications_sms", models.BooleanField(default=True)),
                ("notifications_push", models.BooleanField(default=True)),
                ("notifications_transactions", models.BooleanField(default=True)),
                ("notifications_marketing", models.BooleanField(default=False)),
                ("profil_public", models.BooleanField(default=False)),
                ("afficher_telephone", models.BooleanField(default=False)),
                ("afficher_courriel", models.BooleanField(default=False)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to="identite.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
                "db_table": 'identite"."profils_utilisateurs',
            },
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["courriel"], name="utilisateur_courrie_38773e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["numero_telephone"], name="utilisateur_numero__298b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["type_utilisateur"], name="utilisateur_type_ut_840549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(fields=["statut"], name="utilisateur_statut_cab0f8_idx"),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["niveau_kyc"], name="utilisateur_niveau__ddb718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateur",
            index=models.Index(
                fields=["-date_creation"], name="utilisateur_date_cr_f30656_idx"
            ),
        ),
    ]
