# Generated by Django 4.2.16 on 2026-02-19 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("localisation", "__first__"),
        ("identite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NiveauKYC",
            fields=[
                (
                    "niveau",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "limite_transaction_journaliere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Limite de transaction journalière en devise locale",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "limite_solde_maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solde maximum autorisé",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "documents_requis",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des documents requis pour ce niveau",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Niveau KYC",
                "verbose_name_plural": "Niveaux KYC",
                "db_table": 'identite"."niveaux_kyc',
                "ordering": ["niveau"],
            },
        ),
        migrations.CreateModel(
            name="StatutUtilisateur",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "couleur",
                    models.CharField(
                        default="#000000",
                        help_text="Couleur hexadécimale pour l'affichage (ex: #FF0000)",
                        max_length=7,
                    ),
                ),
                (
                    "permet_connexion",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, l'utilisateur ne peut pas se connecter",
                    ),
                ),
                (
                    "permet_transactions",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, l'utilisateur ne peut pas effectuer de transactions",
                    ),
                ),
                ("ordre_affichage", models.IntegerField(default=0)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statut Utilisateur",
                "verbose_name_plural": "Statuts Utilisateurs",
                "db_table": 'identite"."statuts_utilisateurs',
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeUtilisateur",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("ordre_affichage", models.IntegerField(default=0)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type Utilisateur",
                "verbose_name_plural": "Types Utilisateurs",
                "db_table": 'identite"."types_utilisateurs',
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="derniere_connexion",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="hash_mot_de_passe",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_identite",
                to="localisation.district",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_identite",
                to="localisation.pays",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="point_de_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_identite",
                to="localisation.pointdeservice",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="province_geo",
            field=models.ForeignKey(
                blank=True,
                db_column="province_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_identite",
                to="localisation.province",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="quartier_geo",
            field=models.ForeignKey(
                blank=True,
                db_column="quartier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_identite",
                to="localisation.quartier",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="last_login",
            field=models.DateTimeField(
                blank=True, db_column="derniere_connexion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="password",
            field=models.CharField(db_column="hash_mot_de_passe", max_length=255),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="niveau_kyc",
            field=models.ForeignKey(
                db_column="niveau_kyc",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="identite.niveaukyc",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="statut",
            field=models.ForeignKey(
                db_column="statut",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="identite.statututilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="type_utilisateur",
            field=models.ForeignKey(
                db_column="type_utilisateur",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="identite.typeutilisateur",
            ),
        ),
    ]
