# Generated by Django 4.2.16 on 2026-02-19 20:16

from django.db import migrations


def init_types_utilisateurs(apps, schema_editor):
    """Initialise les types d'utilisateurs"""
    TypeUtilisateur = apps.get_model('identite', 'TypeUtilisateur')
    
    types = [
        {'code': 'CLIENT', 'libelle': 'Client', 'description': 'Client standard de la plateforme', 'ordre_affichage': 1},
        {'code': 'AGENT', 'libelle': 'Agent', 'description': 'Agent de service (dépôt, retrait, etc.)', 'ordre_affichage': 2},
        {'code': 'MARCHAND', 'libelle': 'Marchand', 'description': 'Commerçant acceptant les paiements', 'ordre_affichage': 3},
        {'code': 'ADMIN', 'libelle': 'Administrateur', 'description': 'Administrateur de la plateforme', 'ordre_affichage': 4},
        {'code': 'SUPER_ADMIN', 'libelle': 'Super Administrateur', 'description': 'Super administrateur avec tous les droits', 'ordre_affichage': 5},
        {'code': 'SYSTEME', 'libelle': 'Système', 'description': 'Compte système pour les opérations automatiques', 'ordre_affichage': 6},
    ]
    
    for type_data in types:
        TypeUtilisateur.objects.get_or_create(code=type_data['code'], defaults=type_data)


def init_niveaux_kyc(apps, schema_editor):
    """Initialise les niveaux KYC"""
    NiveauKYC = apps.get_model('identite', 'NiveauKYC')
    
    niveaux = [
        {
            'niveau': 0,
            'libelle': 'Non vérifié',
            'description': 'Aucune vérification effectuée',
            'limite_transaction_journaliere': 0,
            'limite_solde_maximum': 0,
            'documents_requis': [],
        },
        {
            'niveau': 1,
            'libelle': 'Basique',
            'description': 'Vérification basique (téléphone + email)',
            'limite_transaction_journaliere': 50000,
            'limite_solde_maximum': 100000,
            'documents_requis': ['telephone', 'email'],
        },
        {
            'niveau': 2,
            'libelle': 'Complet',
            'description': 'Vérification complète (pièce d\'identité)',
            'limite_transaction_journaliere': 500000,
            'limite_solde_maximum': 2000000,
            'documents_requis': ['telephone', 'email', 'piece_identite', 'selfie'],
        },
        {
            'niveau': 3,
            'libelle': 'Premium',
            'description': 'Vérification premium (justificatif de domicile)',
            'limite_transaction_journaliere': 5000000,
            'limite_solde_maximum': 20000000,
            'documents_requis': ['telephone', 'email', 'piece_identite', 'selfie', 'justificatif_domicile'],
        },
    ]
    
    for niveau_data in niveaux:
        NiveauKYC.objects.get_or_create(niveau=niveau_data['niveau'], defaults=niveau_data)


def init_statuts_utilisateurs(apps, schema_editor):
    """Initialise les statuts utilisateurs"""
    StatutUtilisateur = apps.get_model('identite', 'StatutUtilisateur')
    
    statuts = [
        {
            'code': 'ACTIF',
            'libelle': 'Actif',
            'description': 'Compte actif et opérationnel',
            'couleur': '#28a745',
            'permet_connexion': True,
            'permet_transactions': True,
            'ordre_affichage': 1,
        },
        {
            'code': 'EN_VERIFICATION',
            'libelle': 'En vérification',
            'description': 'Compte en cours de vérification KYC',
            'couleur': '#ffc107',
            'permet_connexion': True,
            'permet_transactions': False,
            'ordre_affichage': 2,
        },
        {
            'code': 'SUSPENDU',
            'libelle': 'Suspendu',
            'description': 'Compte temporairement suspendu',
            'couleur': '#fd7e14',
            'permet_connexion': False,
            'permet_transactions': False,
            'ordre_affichage': 3,
        },
        {
            'code': 'BLOQUE',
            'libelle': 'Bloqué',
            'description': 'Compte bloqué pour raisons de sécurité',
            'couleur': '#dc3545',
            'permet_connexion': False,
            'permet_transactions': False,
            'ordre_affichage': 4,
        },
        {
            'code': 'FERME',
            'libelle': 'Fermé',
            'description': 'Compte définitivement fermé',
            'couleur': '#6c757d',
            'permet_connexion': False,
            'permet_transactions': False,
            'ordre_affichage': 5,
        },
    ]
    
    for statut_data in statuts:
        StatutUtilisateur.objects.get_or_create(code=statut_data['code'], defaults=statut_data)


class Migration(migrations.Migration):

    dependencies = [
        ("identite", "0002_niveaukyc_statututilisateur_typeutilisateur_and_more"),
    ]

    operations = [
        migrations.RunPython(init_types_utilisateurs),
        migrations.RunPython(init_niveaux_kyc),
        migrations.RunPython(init_statuts_utilisateurs),
    ]
