# Generated by Django 4.2.16 on 2026-02-20 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("identite", "0003_init_donnees_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeroTelephone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pays_code_iso_2", models.CharField(db_index=True, max_length=2)),
                ("code_pays", models.CharField(max_length=10)),
                ("numero_national", models.CharField(max_length=20)),
                (
                    "numero_complet",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("numero_formate", models.CharField(blank=True, max_length=30)),
                (
                    "type_numero",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile"),
                            ("FIXE", "Fixe"),
                            ("VOIP", "VoIP"),
                        ],
                        default="MOBILE",
                        max_length=20,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("PERSONNEL", "Personnel"),
                            ("PROFESSIONNEL", "Professionnel"),
                            ("URGENCE", "Urgence"),
                        ],
                        default="PERSONNEL",
                        max_length=20,
                    ),
                ),
                ("est_principal", models.BooleanField(db_index=True, default=False)),
                ("est_verifie", models.BooleanField(db_index=True, default=False)),
                ("date_verification", models.DateTimeField(blank=True, null=True)),
                ("methode_verification", models.CharField(blank=True, max_length=50)),
                (
                    "code_verification_hash",
                    models.CharField(blank=True, max_length=255),
                ),
                ("tentatives_verification", models.IntegerField(default=0)),
                (
                    "derniere_tentative_verification",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU", "Suspendu"),
                            ("BLOQUE", "Bloqué"),
                            ("SUPPRIME", "Supprimé"),
                        ],
                        db_index=True,
                        default="ACTIF",
                        max_length=20,
                    ),
                ),
                ("raison_statut", models.TextField(blank=True)),
                ("date_changement_statut", models.DateTimeField(blank=True, null=True)),
                ("nombre_connexions_reussies", models.IntegerField(default=0)),
                ("nombre_connexions_echouees", models.IntegerField(default=0)),
                ("derniere_connexion", models.DateTimeField(blank=True, null=True)),
                (
                    "derniere_connexion_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("operateur", models.CharField(blank=True, max_length=100)),
                (
                    "type_ligne",
                    models.CharField(
                        blank=True,
                        choices=[("PREPAYE", "Prépayé"), ("POSTPAYE", "Postpayé")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_suppression", models.DateTimeField(blank=True, null=True)),
                ("cree_par", models.UUIDField(blank=True, null=True)),
                ("modifie_par", models.UUIDField(blank=True, null=True)),
                ("metadonnees", models.JSONField(blank=True, default=dict)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeros_telephone",
                        to="identite.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de Téléphone",
                "verbose_name_plural": "Numéros de Téléphone",
                "db_table": 'identite"."numeros_telephone',
            },
        ),
        migrations.CreateModel(
            name="LimiteNumerosParPays",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pays_code_iso_2", models.CharField(max_length=2)),
                ("nombre_max_numeros", models.IntegerField(default=3)),
                ("nombre_max_numeros_verifies", models.IntegerField(default=2)),
                ("autorise_numeros_etrangers", models.BooleanField(default=False)),
                ("pays_autorises_codes", models.JSONField(blank=True, default=list)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "type_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limites_numeros",
                        to="identite.typeutilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limite Numéros par Pays",
                "verbose_name_plural": "Limites Numéros par Pays",
                "db_table": 'identite"."limites_numeros_par_pays',
            },
        ),
        migrations.CreateModel(
            name="HistoriqueNumeroTelephone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("ancien_statut", models.CharField(blank=True, max_length=20)),
                ("nouveau_statut", models.CharField(blank=True, max_length=20)),
                ("raison", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "date_action",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("effectue_par", models.UUIDField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "numero_telephone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="identite.numerotelephone",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_numeros",
                        to="identite.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Numéro Téléphone",
                "verbose_name_plural": "Historiques Numéros Téléphone",
                "db_table": 'identite"."historique_numeros_telephone',
                "ordering": ["-date_action"],
            },
        ),
        migrations.AddIndex(
            model_name="numerotelephone",
            index=models.Index(
                fields=["utilisateur"], name="numeros_tel_utilisa_6b9cb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="numerotelephone",
            index=models.Index(
                fields=["pays_code_iso_2"], name="numeros_tel_pays_co_daebba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="numerotelephone",
            index=models.Index(
                fields=["numero_complet"], name="numeros_tel_numero__0e9578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="numerotelephone",
            index=models.Index(fields=["statut"], name="numeros_tel_statut_460911_idx"),
        ),
        migrations.AddIndex(
            model_name="numerotelephone",
            index=models.Index(
                fields=["est_verifie"], name="numeros_tel_est_ver_9148bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="limitenumerosparpays",
            unique_together={("pays_code_iso_2", "type_utilisateur")},
        ),
        migrations.AddIndex(
            model_name="historiquenumerotelephone",
            index=models.Index(
                fields=["numero_telephone"], name="historique__numero__8666d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiquenumerotelephone",
            index=models.Index(
                fields=["utilisateur"], name="historique__utilisa_5e794d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiquenumerotelephone",
            index=models.Index(
                fields=["-date_action"], name="historique__date_ac_6b9b56_idx"
            ),
        ),
    ]
